import { ChangeEvent, MouseEvent, SyntheticEvent } from "react";

// ============================================================
// ENTITIES (BACKEND avatar)
// ============================================================

export interface Musician {
  id: number;
  name: string;
  avatarIcon?: string; // FontAwesome class, i. e. "fas fa-user"
  genres: string[];
  instruments: string[];
  description?: string;
  // for other fields to add
  // rating?: number;
  // avatar?: string; // if I'd use pic URLs
}

export interface Tag {
  id: number;
  name: string;
  type: "genre" | "instrument";
}

// ============================================================
// REDUX STATE
// ============================================================

export interface AuthState {
  user: { username: string } | null; // или более полный User, если есть
  isAuthenticated: boolean;
}

export interface MusiciansState {
  items: Musician[];
  status: "idle" | "loading" | "succeeded" | "failed";
  error: string | null;
  selectedFilters: string[];
}

// ============================================================
// COMPONENTS PROPS'
// ============================================================

// ---- Modal ----
export interface ModalProps {
  isOpen: boolean;
  onClose: () => void;
  title: React.ReactNode;
  children: React.ReactNode;
}

// ---- MusicianCard ----
export interface MusicianCardProps {
  musician: Musician;
}

// ---- MusicianForm ----
export interface MusicianFormProps {
  initialData?: Partial<Musician>;
  onSubmit: (data: Omit<Musician, "id">) => void | Promise<void>;
  onClose: () => void;
  isEdit: boolean;
}

// ---- TagFilter ----
// (no props here as I use useSelector directly)

// ---- ProtectedRoute ----
export interface ProtectedRouteProps {
  children: React.ReactNode;
}

// ---- HomePage ----
// (no props)

// ---- MusicianPage ----
// (no props)

// ---- LoginPage ----
// (no props)

// ============================================================
// COMMON TYPES FOR APIs / HOOKS
// ============================================================

// Type for login action
export interface LoginPayload {
  username: string;
  // password?: string; // if I'd need
}

// Type for filtering (if I'd need a separate one)
export interface FilterState {
  selectedTags: string[];
  searchQuery?: string;
}

// ============================================================
// TYPES FOR REDUX (RootState, AppDispatch)
// ============================================================

// I'll use these types in store.ts
// They will be taken from store itself but I describe 'em here for clearance
// They're autogenerated in fact

// ============================================================
// AUXILIARY TYPES
// ============================================================

// Type for event change in a form
export type FormChangeEvent = ChangeEvent<
  HTMLInputElement | HTMLTextAreaElement
>;

// Type for a click event
export type ClickEvent = MouseEvent<HTMLButtonElement | HTMLDivElement>;

// Type for form submit event
export type FormSubmitEvent = SyntheticEvent<HTMLFormElement>;

// ============================================================
// OTHER TYPES
// ============================================================

export interface LoginPayload {
  username: string;
}

export interface FilterState {
  selectedTags: string[];
  searchQuery?: string;
}
